name: workflow one

on: push

jobs: 
    job1:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository 
              uses: actions/checkout@v4
            - name: welcome message
              run: echo "GitHub initial"
            - name: list files
              run: ls
            - name: read file
              run: cat README.md